//! Domain types, one module per group of `docs/ANA-9.md` §5 tables.
//!
//! Field names are §5 column names verbatim and enum variant orders are the `CHECK (... IN ...)`
//! orders (plan D3, blueprint B.1/B.3). Every struct derives `Debug, Clone, PartialEq, Serialize,
//! Deserialize`; every enum adds `Copy, Eq, Hash` and is generated by `str_enum!`, so `as_str`
//! and the serde representation can never disagree.

/// Failure of [`core::str::FromStr`] for a database-text enum.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("`{value}` is not a valid {enum_name}")]
pub struct ParseEnumError {
    /// Name of the Rust enum that rejected the value, e.g. `"Status"`.
    pub enum_name: &'static str,
    /// The text that did not match any variant.
    pub value: String,
}

/// Declares a `TEXT NOT NULL CHECK (... IN ...)` column as a Rust enum.
///
/// Generates `ALL` (variants in `CHECK` order), `as_str`, [`core::fmt::Display`],
/// [`core::str::FromStr`] with [`ParseEnumError`], and serde renames driven by the same string
/// literal, so the database text has exactly one definition per variant.
// Textually scoped: every `mod` below is declared after this definition, so the macro is in
// scope in each of them without an import.
macro_rules! str_enum {
    (
        $(#[$enum_meta:meta])*
        $name:ident {
            $( $(#[$variant_meta:meta])* $variant:ident => $text:literal ),+ $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
        #[cfg_attr(feature = "sqlx", derive(sqlx::Type))]
        #[cfg_attr(feature = "sqlx", sqlx(type_name = "text"))]
        pub enum $name {
            $(
                $(#[$variant_meta])*
                #[serde(rename = $text)]
                #[cfg_attr(feature = "sqlx", sqlx(rename = $text))]
                $variant,
            )+
        }

        impl $name {
            #[doc = concat!("Every `", stringify!($name), "` variant, in DDL `CHECK` order.")]
            pub const ALL: &'static [Self] = &[$(Self::$variant),+];

            #[doc = concat!("The database text of this `", stringify!($name), "`.")]
            #[must_use]
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $text,)+
                }
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl ::core::str::FromStr for $name {
            type Err = $crate::model::ParseEnumError;

            fn from_str(s: &str) -> ::core::result::Result<Self, Self::Err> {
                match s {
                    $($text => Ok(Self::$variant),)+
                    other => Err($crate::model::ParseEnumError {
                        enum_name: stringify!($name),
                        value: other.to_owned(),
                    }),
                }
            }
        }
    };
}

pub mod agent;
pub mod box_;
pub mod document;
pub mod event;
pub mod hierarchy;
pub mod ids;
pub mod item;
pub mod kind;
pub mod link;
pub mod note;
pub mod overlap;
pub mod quota;
pub mod run;
pub mod scope;
pub mod skill;
pub mod usage;
pub mod user;

pub use agent::{Agent, AgentBox, AgentSummary, Billing, Transport};
pub use box_::{
    BoxInfo, BoxProfile, BoxRow, BoxSettings, BoxTool, DEFAULT_MAX_CONCURRENT_ITEMS, OsFamily,
};
pub use document::{Document, DocumentHead, NewDocument, ResolvedInput};
pub use event::{EventKind, EventRole, SessionEvent};
pub use hierarchy::{
    NewProject, NewRepo, NewWorkspace, Project, ProjectPatch, ProjectRef, Repo, RepoBoxPath,
    RepoPatch, Workspace, WorkspaceBoxPath, WorkspacePatch, WorkspaceProject, WorkspaceSummary,
};
pub use ids::{
    AgentId, BoxId, CommandRunId, DocumentId, ItemId, ItemKindId, NoteId, PhaseId, ProjectId,
    PromptTemplateId, RepoId, RunId, SkillBindingId, SkillId, StepGraphId, StepId, UserId,
    WorkspaceId,
};
pub use item::{Item, ItemFilter, ItemPatch, ItemRevision, ItemSummary, NewItem, Status};
pub use kind::{
    CommandQueue, Gate, Isolation, ItemKind, ItemKindPatch, NewItemKind, NewStepGraph, PhaseAgent,
    PhasePatch, ProjectSettings, PromptTemplate, ResolvedGraph, ResolvedPhase, StepGraph,
    StepGraphPatch, StepGraphPhase,
};
pub use link::{ItemLink, LinkEdge, LinkGraph, LinkKind, LinkNode, UpstreamEntry};
pub use note::{NewNote, Note};
pub use overlap::{Claim, OverlapRule, RepoScope, RunScope, overlaps, scope_of};
pub use quota::{
    Availability, CapError, PER_TOKEN_CAP_BATCH, PER_TOKEN_CAP_RUN, ProjectCaps, Quota,
    QuotaSource, QuotaWindow, SkipReason, Spend, available, normalize,
};
pub use run::{
    ChatRunSpec, CommandRun, CommandRunStatus, GateOutcome, GraphSnapshot, NewCommandRun, NewRun,
    NewRunStep, Run, RunKind, RunMode, RunStatus, RunStep, RunStepCommit, RunStepSummary,
    RunStepTree, RunSummary, SnapshotCandidate, SnapshotGraph, SnapshotJudge, SnapshotPhase,
    SnapshotSettings, SnapshotTemplate, StepOutcome, StepStatus, TIMESTAMPTZ_DIGITS, VerifyOutcome,
    prompt_summary,
};
pub use scope::{PromptScope, Scope};
pub use skill::{BoundSkill, Skill, SkillBinding, SkillVersion};
pub use usage::UsageTotals;
pub use user::{AppUser, CapabilityTag};

#[cfg(test)]
mod tests {
    use super::*;
    use core::fmt::{Debug, Display};
    use core::str::FromStr;
    use serde::Serialize;
    use serde::de::DeserializeOwned;
    use uuid::Uuid;

    /// Asserts that `ALL` matches the DDL `CHECK` list exactly (same values, same order) and that
    /// every variant round-trips through `as_str` / `FromStr` / serde.
    fn check_enum<T>(all: &[T], texts: &[&str])
    where
        T: Copy + Debug + PartialEq + Display + FromStr + Serialize + DeserializeOwned,
        <T as FromStr>::Err: Debug,
    {
        assert_eq!(
            all.len(),
            texts.len(),
            "variant count differs from the CHECK list"
        );
        for (variant, text) in all.iter().zip(texts) {
            assert_eq!(&variant.to_string(), text, "as_str / CHECK order mismatch");
            let parsed = T::from_str(text).expect("CHECK text parses");
            assert_eq!(&parsed, variant, "FromStr round-trip");
            let json = serde_json::to_string(variant).expect("serialize");
            assert_eq!(json, format!("\"{text}\""), "serde rename follows as_str");
            let back: T = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(&back, variant, "serde round-trip");
        }
    }

    #[test]
    fn status_matches_check_list() {
        check_enum(
            Status::ALL,
            &[
                "open",
                "queued",
                "in_progress",
                "awaiting_approval",
                "blocked",
                "done",
                "failed",
                "closed",
            ],
        );
    }

    #[test]
    fn link_kind_matches_check_list() {
        check_enum(
            LinkKind::ALL,
            &["blocked_by", "origin", "relates", "supersedes"],
        );
    }

    #[test]
    fn run_enums_match_check_lists() {
        check_enum(RunKind::ALL, &["graph", "chat"]);
        check_enum(RunMode::ALL, &["manual", "auto"]);
        check_enum(
            RunStatus::ALL,
            &[
                "queued",
                "running",
                "awaiting_approval",
                "done",
                "failed",
                "cancelled",
            ],
        );
        check_enum(
            StepStatus::ALL,
            &[
                "pending",
                "running",
                "awaiting_approval",
                "done",
                "failed",
                "cancelled",
                "superseded",
            ],
        );
        check_enum(
            GateOutcome::ALL,
            &["approved", "rejected", "retried", "skipped"],
        );
        check_enum(VerifyOutcome::ALL, &["pass", "fail", "unavailable"]);
        check_enum(
            CommandRunStatus::ALL,
            &["queued", "running", "done", "failed", "cancelled"],
        );
    }

    #[test]
    fn event_enums_match_check_lists() {
        check_enum(
            EventKind::ALL,
            &[
                "prompt",
                "follow_up",
                "assistant_text",
                "thought",
                "tool_call",
                "tool_result",
                "edit_proposal",
                "permission_request",
                "permission_answer",
                "plan",
                "usage",
                "error",
                "done",
                "other",
            ],
        );
        check_enum(EventRole::ALL, &["user", "agent", "htui"]);
    }

    #[test]
    fn box_and_agent_enums_match_check_lists() {
        check_enum(OsFamily::ALL, &["windows", "linux", "macos"]);
        check_enum(Transport::ALL, &["acp", "cli"]);
        check_enum(Billing::ALL, &["subscription", "per_token"]);
    }

    #[test]
    fn phase_enums_match_check_lists() {
        check_enum(Gate::ALL, &["always", "on_failure", "never"]);
        check_enum(
            Isolation::ALL,
            &["worktree", "copy", "shared_serialized", "local"],
        );
        check_enum(CommandQueue::ALL, &["off", "fan_out_only", "always"]);
    }

    #[test]
    fn unknown_enum_text_is_rejected() {
        let err = Status::from_str("archived").expect_err("not a CHECK value");
        assert_eq!(
            err,
            ParseEnumError {
                enum_name: "Status",
                value: "archived".to_owned()
            }
        );
        assert_eq!(err.to_string(), "`archived` is not a valid Status");
        assert!(RunKind::from_str("").is_err());
    }

    #[test]
    fn status_terminality_matches_readiness_rule() {
        for status in Status::ALL {
            assert_eq!(
                status.is_terminal(),
                matches!(status, Status::Done | Status::Closed),
                "{status} terminality"
            );
        }
    }

    #[test]
    fn run_status_activity_matches_top_bar_rule() {
        for status in RunStatus::ALL {
            assert_eq!(
                status.is_active(),
                matches!(
                    status,
                    RunStatus::Queued | RunStatus::Running | RunStatus::AwaitingApproval
                ),
                "{status} activity"
            );
        }
    }

    /// Asserts a `Display` / `FromStr` / serde round-trip and that the serde form is transparent
    /// (identical to the wrapped `Uuid`).
    fn check_id<T>(id: T, inner: Uuid)
    where
        T: Copy + Debug + PartialEq + Display + FromStr + Serialize + DeserializeOwned,
        <T as FromStr>::Err: Debug,
    {
        assert_eq!(id.to_string(), inner.hyphenated().to_string());
        let parsed = T::from_str(&id.to_string()).expect("hyphenated uuid parses");
        assert_eq!(parsed, id);
        let json = serde_json::to_string(&id).expect("serialize");
        assert_eq!(json, serde_json::to_string(&inner).expect("serialize uuid"));
        let back: T = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, id);
    }

    #[test]
    fn id_newtypes_round_trip() {
        let u = Uuid::now_v7();
        check_id(UserId::from_uuid(u), u);
        check_id(BoxId::from_uuid(u), u);
        check_id(WorkspaceId::from_uuid(u), u);
        check_id(ProjectId::from_uuid(u), u);
        check_id(RepoId::from_uuid(u), u);
        check_id(ItemKindId::from_uuid(u), u);
        check_id(ItemId::from_uuid(u), u);
        check_id(NoteId::from_uuid(u), u);
        check_id(DocumentId::from_uuid(u), u);
        check_id(StepGraphId::from_uuid(u), u);
        check_id(PhaseId::from_uuid(u), u);
        check_id(PromptTemplateId::from_uuid(u), u);
        check_id(AgentId::from_uuid(u), u);
        check_id(RunId::from_uuid(u), u);
        check_id(StepId::from_uuid(u), u);
        check_id(SkillId::from_uuid(u), u);
        check_id(SkillBindingId::from_uuid(u), u);
        check_id(CommandRunId::from_uuid(u), u);
    }

    #[test]
    fn minted_ids_are_distinct_and_v7() {
        let a = ItemId::new();
        let b = ItemId::new();
        assert_ne!(a, b, "each mint is a fresh UUID");
        assert_eq!(a.as_uuid().get_version_num(), 7, "§3: client-side UUIDv7");
        assert!(a < b, "v7 is time-ordered, so B-tree inserts stay ordered");
        assert!(ItemId::from_str("not-a-uuid").is_err());
    }

    #[test]
    fn scope_orders_project_ids_by_position() {
        let ws = WorkspaceSummary {
            workspace_id: WorkspaceId::new(),
            slug: "core".to_owned(),
            name: "Core".to_owned(),
            projects: vec![
                ProjectRef {
                    project_id: ProjectId::from_uuid(Uuid::from_u128(3)),
                    slug: "third".to_owned(),
                    name: "Third".to_owned(),
                    position: 2,
                },
                ProjectRef {
                    project_id: ProjectId::from_uuid(Uuid::from_u128(1)),
                    slug: "first".to_owned(),
                    name: "First".to_owned(),
                    position: 0,
                },
                ProjectRef {
                    project_id: ProjectId::from_uuid(Uuid::from_u128(2)),
                    slug: "second".to_owned(),
                    name: "Second".to_owned(),
                    position: 1,
                },
            ],
        };

        let scope = Scope::from_workspace(&ws);

        assert_eq!(scope.workspace_id, ws.workspace_id);
        assert_eq!(
            scope.project_ids,
            vec![
                ProjectId::from_uuid(Uuid::from_u128(1)),
                ProjectId::from_uuid(Uuid::from_u128(2)),
                ProjectId::from_uuid(Uuid::from_u128(3)),
            ]
        );
        assert!(scope.contains(ProjectId::from_uuid(Uuid::from_u128(2))));
        assert!(!scope.contains(ProjectId::new()));
        assert!(!scope.is_empty());
    }

    #[test]
    fn scope_of_an_empty_workspace_is_empty() {
        let ws = WorkspaceSummary {
            workspace_id: WorkspaceId::new(),
            slug: "empty".to_owned(),
            name: "Empty".to_owned(),
            projects: Vec::new(),
        };
        assert!(Scope::from_workspace(&ws).is_empty());
    }
}
